---
all:
  children:
    app_servers:
      hosts:
        app_server1:
          ansible_host: 10.0.0.7
          ansible_user: dev_user
          ansible_python_interpreter: /usr/bin/python3.9

    db_servers:
      hosts:
        db_server1:
          ansible_host: 10.0.0.7
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3.9
    
    privileged_servers:
      hosts:
        app_server1:
          ansible_host: 10.0.0.7
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3.9