---
user: "dev_user"
java_version: "21.0.5"
java_archive: "jdk-{{ java_version }}_linux-x64_bin.tar.gz"
java_remote_copy_path: "/tmp/{{ java_archive }}"
java_install_dir: "/home/{{ user }}/jdk"
java_home: "{{ java_install_dir }}/jdk-{{java_version}}"
java_env_vars:
  - "export JAVA_HOME={{ java_home }}"
  - "export PATH=$PATH:$JAVA_HOME/bin"